---
deployment:
  tasks:
    - export DEPLOYPATH=/home/loretosistemas/public_html/apidiagnostica/
    - cd /home/loretosistemas/repositories/diagnostica/
    - git fetch
    - git diff --name-only origin/main | xargs -I{} cp --parents {} $DEPLOYPATH